---

# This task installs Insync Google Drive client.
# https://www.insynchq.com/

- name: Add Insync GPG key to allow apt to authenticate the Insync repository
  tags: insync
  become: yes
  become_user: root
  become_method: sudo
  apt_key: keyserver=keyserver.ubuntu.com id=ACCAF35C state=present validate_certs=yes

- name: Install Insync APT source list
  tags: insync
  become: yes
  become_user: root
  become_method: sudo
  copy: src=insync.list dest=/etc/apt/sources.list.d/insync.list mode=0644

- name: Update repositories cache
  tags: insync
  become: yes
  become_user: root
  become_method: sudo
  apt:
    update_cache: yes

- name: Install Insync Google Drive client
  tags: insync
  become: yes
  become_user: root
  become_method: sudo
  apt: name=insync state=present
