---

# This task installs the preferred packages available from Ubuntu repositories.

- name: Install preferred Ubuntu provided packages
  tags: system, install_packages
  become: yes
  become_user: root
  become_method: sudo
  apt: name={{item}} state=present
  with_items:
    # editors
    - vim
    - sublime-text
    # command-line utils
    - sudo
    - sed
    - gawk
    - grep
    - diffutils
    - patch
    - fdupes
    - ncdu
    - tree
    - atop
    - htop
    - iotop
    - iftop
    - powertop
    - mc
    - gnuplot
    # internet
    - wget
    - curl
    - skype
    - filezilla
    # firewall
    - ufw
    - gufw
    # multimedia
    - vlc
    - gimp
    - hugin
    - calibre
    # archives
    - tar
    - zip
    - unzip
    - rar
    - unrar
    - p7zip
    - xz-utils
    # gui utils
    - meld
    - terminator
    - redshift
    - redshift-gtk
    - dropbox
    - sysinfo
    - workrave
    # fonts
    - ttf-mscorefonts-installer
    - fonts-inconsolata
    # development
    - git
    - gitg
    - gcc
    - g++
    - build-essential
