---

# This task updates the installed packages to the latest available version.

- name: Update packages to latest
  tags: system, update
  become: yes
  become_user: root
  become_method: sudo
  apt:
    update_cache: yes
    upgrade: yes
