---

# This task installs Atom text editor.
# https://atom.io/

- name: Create temporary work directory
  tags: atom
  file: path={{tmpDir}} state=directory mode=0755

- name: Download package
  tags: atom
  get_url:
    url: "{{url}}"
    dest: "{{tmpDir}}/{{package}}"
    mode: 0644

- name: Install package
  tags: atom
  become: yes
  become_user: root
  become_method: sudo
  command: chdir={{tmpDir}} dpkg -i {{package}}

- name: Cleanup
  tags: atom
  file: path={{tmpDir}} state=absent
